version: '3.9'

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: ${POSTGRES_CONTAINER}
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSW}
      - POSTGRES_DB=${DB}
    ports:
      - ${PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB} -g ${HOST} -p ${PORT} -u ${USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-data:
