version: '3.9'

services:
  db:
    image: "mysql:${MYSQL_VERSION}"
    container_name: ${MYSQL_CONTAINER}
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSW}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSW}
    ports:
      - ${PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h ${HOST} -u $${USER} --password=$${PASSW}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  db-data:
